import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/redux/ReduxProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { McLaren } from "next/font/google";
import ReactQueryWrapper from "../components/ReactQueryWrapper";

// Yatra_One
// Sriracha
// Commissioner

const dmSerifDisplay = McLaren({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSerifDisplay.className}`}>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ReactQueryWrapper>
              {children}
            </ReactQueryWrapper>
          </ThemeProvider>
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
