apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: 324037317995.dkr.ecr.us-east-1.amazonaws.com/admin-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: FRONT_END_URL
              value: "http://localhost:3000"
            - name: CLIENT_URL
              value: "localhost"
            - name: GATEWAY_URL
              value: "gateway-service"
            - name: USER_SERVER_URL
              value: "user-service"
            - name: VERIFICATION_TOKEN_SECRET
              value: "d13d23qwe341r342e23eqe32"
            - name: ACCESS_TOKEN_SECRET
              value: "your-access-token-secret"
            - name: REFRESH_TOKEN_SECRET
              value: "your-refresh-token-secret"
            # - name: DIRECT_URL
            #   value: "postgresql://postgres.hnzqywzpwpxpzolkgilg:hireArenaPostgressPassword@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true&statement_cache_mode=describe"
            - name: DATABASE_URL
              value: "postgresql://postgres.hnzqywzpwpxpzolkgilg:hireArenaPostgressPassword@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - port: 5003
      targetPort: 5003
