apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: 324037317995.dkr.ecr.us-east-1.amazonaws.com/chat-service:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5009
            - containerPort: 5010
          env:
            - name: PORT
              value: "5009"
            - name: MONGO_DB
              value: "mongodb+srv://hireArenaKey1:hireArenaKey1Password@hirearenacluster.xiics9u.mongodb.net/chat_db"
            - name: JOB_SERVER_URL
              value: "job-server:5011"
            - name: USER_SERVER_URL
              value: "user-service:5051"
            - name: ACCESS_TOKEN_SECRET
              value: "your-access-token-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      port: 5009
      targetPort: 5009
    - name: grpc
      port: 5010
      targetPort: 5010