apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: 324037317995.dkr.ecr.us-east-1.amazonaws.com/job-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
            - containerPort: 5015
          env:
            - name: FRONT_END_URL
              value: "http://localhost:3000"
            - name: GRPC_PORT
              value: "5015"
              # value: "postgresql://postgres.nhwnprxllzsdskaablpn:PvO5P8aKILzRxYlX@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer:true"
            # - name: DIRECT_URL
            - name: DATABASE_URL
              value: "postgresql://postgres.nhwnprxllzsdskaablpn:PvO5P8aKILzRxYlX@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
            - name: VERIFICATION_TOKEN_SECRET
              value: "d13d23qwe341r342e23eqe32"
            - name: ACCESS_TOKEN_SECRET
              value: "your-access-token-secret"
            - name: REFRESH_TOKEN_SECRET
              value: "your-refresh-token-secret"
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "your-redis-password (optional)"
            - name: USER_SERVER_URL
              value: "user-service:5051"
            - name: INTERVIEW_SERVER_URL
              value: "interview-management-service:5007"
            - name: CHAT_SERVER_URL
              value: "chat-service:5010"
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002
    - name: grpc
      port: 5015
      targetPort: 5015