global:
     scrape_interval: 15s
     evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:4000']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5000']
  - job_name: 'job-service'
    static_configs:
      - targets: ['job-service:5002']
  - job_name: 'interview-management-service'
    static_configs:
      - targets: ['interview-management-service:5006']
  # - job_name: 'file-service'
  #   static_configs:
  #     - targets: ['file-service:5004']
  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:5003']
  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:5009']
  # - job_name: 'video-service'
  #   static_configs:
  #     - targets: ['video-service:5013']
  # - job_name: 'client'
  #   static_configs:
  #     - targets: ['client:3000']