apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: 324037317995.dkr.ecr.us-east-1.amazonaws.com/video-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5013
          env:
            - name: PORT
              value: "5013"
            - name: MONGO_DB
              value: "mongodb+srv://hireArenaKey1:hireArenaKey1Password@hirearenacluster.xiics9u.mongodb.net/video_db"
            - name: ACCESS_TOKEN_SECRET
              value: "your-access-token-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video-service
  ports:
    - port: 5013
      targetPort: 5013
      protocol: TCP
  type: ClusterIP


